### ISSUE TITLE
if I build the optional app as opposed to let the pipeline build the app I run into this following error:

### ISSUE THREAD

**Issue by ylehilds** [byu-oit/hello-world-api#24]
Error: Error in function call

  on ../../modules/app/main.tf line 122, in resource "aws_lambda_function" "test_lambda":
 122:   source_code_hash = filebase64sha256("../../../tst/codedeploy-hooks/after-allow-test-traffic/lambda.zip")

Call to function "filebase64sha256" failed: no file exists at
../../../tst/codedeploy-hooks/after-allow-test-traffic/lambda.zip.

**Comment by GaryGSC** [comment]
Closed by #29.
