### ISSUE TITLE
Default Tagging in AWS Provider >=v3.38.0

### ISSUE THREAD

**Issue by stuft2** [byu-oit/hello-world-api#385]
While updating dependencies for a project based on our hello-world templates, I ran into this error during a `terraform apply`:

> Error: "tags" are identical to those in the "default_tags" configuration block of the provider: please de-duplicate and try again

In researching this error I ran across an article that described a relatively new feature in the Terraform AWS Provider:
> In version 3.38.0 and later of the Terraform AWS Provider, a default_tags argument is available in the provider configuration block. This argument allows for tagging of all resources that currently support the tags argument. **It is intended as an alternative to the tedium of applying the same tags repeatedly across all resources**.

We defined some [default tags as local variables in our template](https://github.com/byu-oit/hw-fargate-api/blob/7df7f812e40b3eff5e4a314aa3f52c7f4c11bb07/terraform-iac/modules/app/main.tf#L23) so that we can pass them into resources. With newer versions of the AWS Provider, passing in duplicate or partially duplicate tags into resources causes the plan to fail. We should update this and other hello-world templates to only supply the default tags in the AWS Provider block like so:

```
locals {
  env = "dev"
}
provider "aws" {
  region = "us-west-2"

  default_tags {
    tags = {
      repo             = "https://github.com/byu-oit/hw-fargate-api"
      data-sensitivity = "public"
      env              = local.env
    }
  }
}
```

References:
- [Known Issues with Default Tags in the Terraform AWS Provider](https://support.hashicorp.com/hc/en-us/articles/4406026108435-Known-issues-with-default-tags-in-the-Terraform-AWS-Provider)
- [GitHub Issue](https://github.com/hashicorp/terraform-provider-aws/issues/19204)

**Comment by Gi60s** [comment]
Story created and added to the backlog: STRY0060840

**Comment by joanna-hugo** [comment]
I wrote a PR to fix this problem in this repo (see link above) and it looks like it's already fixed in the other HW template repos
